export const categoryEmojiOptions = [
  ['🍎', 'apple fruit groceries food'],
  ['🥑', 'avocado fruit groceries food'],
  ['🍞', 'bread bakery groceries food'],
  ['🥦', 'vegetables groceries food'],
  ['☕', 'coffee cafe drink food'],
  ['🍽️', 'dining restaurant food'],
  ['🍕', 'pizza restaurant food'],
  ['🛒', 'groceries shopping food'],
  ['🚕', 'taxi cab transport travel'],
  ['🚆', 'train transport travel'],
  ['✈️', 'flight airplane travel'],
  ['🚗', 'car fuel transport'],
  ['⛽', 'fuel petrol transport'],
  ['🏠', 'home rent house bills'],
  ['💡', 'electricity power bills home'],
  ['📱', 'phone mobile bills'],
  ['🌐', 'internet broadband bills'],
  ['🛍️', 'shopping clothes retail'],
  ['👕', 'clothes fashion shopping'],
  ['💄', 'beauty skincare shopping'],
  ['🎬', 'movies cinema entertainment'],
  ['🎮', 'games gaming entertainment'],
  ['🎵', 'music entertainment'],
  ['🎟️', 'events tickets entertainment'],
  ['🏋️', 'gym fitness health'],
  ['💊', 'medicine pharmacy health'],
  ['🩺', 'doctor healthcare health'],
  ['📚', 'books education learning'],
  ['🎓', 'education tuition school'],
  ['🐾', 'pet animal vet'],
  ['🐶', 'dog pet animal'],
  ['🐱', 'cat pet animal'],
  ['👶', 'child family'],
  ['🎁', 'gift present'],
  ['💳', 'card payment finance'],
  ['🏦', 'bank finance'],
  ['💰', 'savings money income'],
  ['💵', 'cash money income'],
  ['💼', 'salary work income'],
  ['📈', 'investment growth income'],
  ['🧾', 'receipt tax bills'],
  ['🧹', 'cleaning home'],
  ['🔧', 'repair maintenance home'],
  ['🌱', 'garden home'],
  ['🏖️', 'holiday vacation travel'],
  ['💝', 'charity donation'],
  ['🧘', 'wellness health'],
  ['✨', 'other favorite'],
] as const;
