'use client';

import React from 'react';
import { ArrowDownRight, ArrowLeft, ArrowUpRight, ArrowLeftRight, UsersRound, Wallet, Tag } from 'lucide-react';
import { Button } from '@finapp/ui/web';
import { CurrencyInput } from './CurrencyInput';
import { DateTimePicker } from './DateTimePicker';
import { TransactionTable, type TransactionTableItem } from './TransactionsScreen';
import styles from './Transactions.module.css';

export type TransactionFormType = 'expense' | 'income' | 'transfer';
export type TransactionFormOption = { id: string; name: string; currency?: string; icon?: string };
export type TransactionFormScreenProps = {
  mode: 'create' | 'edit';
  type: TransactionFormType;
  title: string;
  amount: string;
  merchant: string;
  note: string;
  occurredAt: number;
  hasTime: boolean;
  currency: string;
  accounts: readonly TransactionFormOption[];
  categories: readonly TransactionFormOption[];
  accountId: string;
  categoryId: string;
  destinationId: string;
  loading?: boolean;
  saving?: boolean;
  error?: string | null;
  dataError?: string | null;
  isDefaultAccount?: boolean;
  isDefaultCategory?: boolean;
  savingDefault?: boolean;
  onTypeChange: (type: TransactionFormType) => void;
  onTitleChange: (value: string) => void;
  onAmountChange: (value: string) => void;
  onMerchantChange: (value: string) => void;
  onNoteChange: (value: string) => void;
  onAccountChange: (id: string) => void;
  onCategoryChange: (id: string) => void;
  onDestinationChange: (id: string) => void;
  onDateChange: (value: number) => void;
  onHasTimeChange: (enabled: boolean) => void;
  onSubmit: (event: React.FormEvent<HTMLFormElement>) => void;
  onBack: () => void;
  onToggleDefault?: (selection: 'account' | 'category') => void;
  onAddAccount?: () => void;
  onManageCategories?: () => void;
  onSplitExpense?: () => void;
  signedIn?: boolean;
  unavailableMessage?: string;
  submitDisabled?: boolean;
  status?: string;
  referenceId?: string;
  similarTransactions?: readonly TransactionTableItem[];
  onOpenTransaction?: (id: string) => void;
};

export function TransactionFormScreen(p: TransactionFormScreenProps) {
  const account = p.accounts.find(item => item.id === p.accountId);
  const category = p.categories.find(item => item.id === p.categoryId);
  const destinations = p.accounts.filter(item => item.id !== p.accountId && item.currency === account?.currency);
  if (!p.signedIn && p.signedIn !== undefined) return <main className={styles.page}>Sign in to manage your personal transactions.</main>;
  if (p.unavailableMessage) return <main className={styles.page}><p role="alert" className={styles.error}>{p.unavailableMessage}</p></main>;
  if (p.loading) return <main className={styles.page}><p role="status">Loading transaction options…</p></main>;
  const field = (label: string, control: React.ReactNode, wide = false) => <div className={`${styles.field} ${wide ? styles.wide : ''}`}><span>{label}<span className={styles.required}>{['Title','Amount','Category','Account','Date','From account','To account'].includes(label) ? ' *' : ''}</span></span>{control}</div>;
  const select = (label: string, value: string, options: readonly TransactionFormOption[], change: (id:string)=>void) => <select aria-label={label} value={value} onChange={e=>change(e.target.value)}><option value="">Choose {label.toLowerCase()}</option>{options.map(item=><option key={item.id} value={item.id}>{item.name}{item.currency ? ` · ${item.currency}` : ''}</option>)}</select>;
  const types = <div className={styles.typeGroup}>{(['expense','income','transfer'] as const).map((value)=>{const Icon=value==='expense'?ArrowDownRight:value==='income'?ArrowUpRight:ArrowLeftRight;return <button key={value} type="button" aria-pressed={p.type===value} className={`${styles.typeButton} ${p.type===value?styles.selected:''}`} onClick={()=>p.onTypeChange(value)}><Icon size={19}/>{value[0]!.toUpperCase()+value.slice(1)}</button>})}</div>;
  return <main className={styles.page}><button type="button" className={styles.back} onClick={p.onBack}><ArrowLeft size={17}/>{p.mode==='create'?'Back to transactions':'Transactions / Edit transaction'}</button><header><h1 className={styles.heading}>{p.mode==='create'?'New transaction':'Edit transaction'}</h1><p className={styles.subtitle}>{p.mode==='create'?'Add a new income or expense to keep your finances up to date.':'Update the details of this transaction.'}</p></header><div className={p.mode==='create'?styles.create:styles.formLayout}><form onSubmit={p.onSubmit} className={`${styles.panel} ${styles.form}`}><div className={styles.fields}>{field('Transaction type',types,p.mode==='edit')}{p.type!=='transfer'&&field('Title',<input className={styles.input} aria-label="Transaction title" placeholder="e.g. Grocery shopping, Salary, Rent…" value={p.title} onChange={e=>p.onTitleChange(e.target.value)} maxLength={120}/>)}{field('Amount',<CurrencyInput currency={account?.currency??p.currency} value={p.amount} onChangeText={p.onAmountChange}/>)}{p.type!=='transfer'&&field('Category',select('Category',p.categoryId,p.categories,p.onCategoryChange))}{field(p.type==='transfer'?'From account':'Account',select('Account',p.accountId,p.accounts,p.onAccountChange))}{p.type==='transfer'&&field('To account',select('Destination account',p.destinationId,destinations,p.onDestinationChange))}{field('Date',<div><DateTimePicker value={p.occurredAt} showTime={p.hasTime} onChange={p.onDateChange}/><label className={styles.help}><input type="checkbox" checked={p.hasTime} onChange={e=>p.onHasTimeChange(e.target.checked)}/> Include time</label></div>)}{field('Merchant / Payee',<input className={styles.input} aria-label="Merchant or payee" placeholder="e.g. Zomato, Amazon, Electricity Board…" value={p.merchant} onChange={e=>p.onMerchantChange(e.target.value)} maxLength={120}/>)}{field('Notes',<textarea aria-label="Transaction note" placeholder="Add a note (optional)…" value={p.note} onChange={e=>p.onNoteChange(e.target.value)} maxLength={500} rows={3}/>,true)}{p.mode==='edit'&&field('Status',<div className={styles.input}>{p.status??'Saved'}</div>)}{p.mode==='edit'&&p.referenceId&&field('Transaction ID / Reference',<div className={styles.input}>{p.referenceId}</div>)}</div>{p.mode==='create'&&<div className={styles.options}>{p.onToggleDefault&&<button type="button" className={styles.option} disabled={p.savingDefault||!account} onClick={()=>p.onToggleDefault?.('account')}><Wallet size={23}/><span>Default account<small>Use this account for new transactions</small></span><input type="checkbox" tabIndex={-1} readOnly checked={p.isDefaultAccount}/></button>}{p.onToggleDefault&&p.type!=='transfer'&&<button type="button" className={styles.option} disabled={p.savingDefault||!category} onClick={()=>p.onToggleDefault?.('category')}><Tag size={23}/><span>Default category<small>Use this category next time</small></span><input type="checkbox" tabIndex={-1} readOnly checked={p.isDefaultCategory}/></button>}{p.type==='expense'&&p.onSplitExpense&&<button type="button" className={styles.option} onClick={p.onSplitExpense}><UsersRound size={23}/><span>Split this transaction<small>Share this expense across multiple people</small></span></button>}</div>}{!p.accounts.length&&<p className={styles.help}>No available accounts. <button type="button" onClick={p.onAddAccount}>Add an account</button></p>}{p.type!=='transfer'&&!p.categories.length&&<p className={styles.help}>No available categories. <button type="button" onClick={p.onManageCategories}>Create a category</button></p>}{p.dataError&&<p role="alert" className={styles.error}>{p.dataError}</p>}{p.error&&<p role="alert" className={styles.error}>{p.error}</p>}<footer className={styles.footer}><Button type="button" variant="outline" onPress={p.onBack}>Cancel</Button><Button type="submit" disabled={p.saving||p.submitDisabled}>{p.saving?'Saving…':p.mode==='create'?'Add transaction':'Save changes'}</Button></footer></form>{p.mode==='edit'&&<aside className={styles.aside}><section className={styles.panel}><h2 className={styles.sectionTitle}>Transaction impact</h2><p className={styles.subtitle}>How this change affects your finances.</p><dl className={styles.details}>{[['Amount',`${p.amount||'0'} ${account?.currency??p.currency}`],['Category',p.type==='transfer'?'Transfer':category?.name??'Uncategorized'],['Account',account?.name??'Unassigned'],['Date',new Date(p.occurredAt).toLocaleDateString()],['Status',p.status??'Saved']].map(([label,value])=><React.Fragment key={label}><dt>{label}</dt><dd>{value}</dd></React.Fragment>)}</dl><p className={styles.help}>Saving updates this transaction in your account{p.type!=='transfer'?' and category totals':''}.</p></section><section className={styles.panel}><h2 className={styles.sectionTitle}>Recent similar transactions</h2><p className={styles.subtitle}>Other transactions in this category or at this merchant.</p><div style={{overflowX:'auto',marginTop:14}}><TransactionTable items={p.similarTransactions??[]} onSelect={p.onOpenTransaction} compact/></div></section></aside>}</div></main>;
}
