'use client';
import React from 'react';
import { ArrowDownRight, ArrowUpRight, BarChart3, ChevronRight, Plus, Search, Wallet } from 'lucide-react';
import { CategoryIcon } from './CategoryIcon';
import { Money } from './Money';
import type { TransactionType } from '../types';
import styles from './Transactions.module.css';
import { compareTransactionAmounts } from '../transactionComparison';

export type TransactionTableItem = { id: string; title: string; note?: string; merchant?: string; category: string; categoryIcon?: string; account?: string; destination?: string; date: string; amountMinor: bigint; currency: string; type: TransactionType };
export function TransactionTable({items,onSelect,compact=false}: {items: readonly TransactionTableItem[];onSelect?: (id:string)=>void;compact?:boolean}) {
 return items.length ? <table className={styles.table}><thead><tr><th>#</th><th>Description</th>{!compact&&<><th>Category</th><th>Account</th></>}<th>Date</th><th style={{textAlign:'right'}}>Amount</th><th /></tr></thead><tbody>{items.map((item,index)=><tr key={item.id} tabIndex={onSelect?0:undefined} onClick={()=>onSelect?.(item.id)} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();onSelect?.(item.id);}}}><td>{index+1}</td><td><div className={styles.identity}><CategoryIcon label={item.category} icon={item.categoryIcon}/><span><strong>{item.title}</strong><small>{item.note||item.merchant}</small></span></div></td>{!compact&&<><td><span className={styles.chip}><CategoryIcon label={item.category} icon={item.categoryIcon}/>{item.category}</span></td><td>{item.account||'Unassigned'}{item.destination&&` → ${item.destination}`}</td></>}<td>{item.date}</td><td className={`${styles.amount} ${item.type==='income'||item.type==='refund'?styles.income:styles.expense}`}><Money amountMinor={item.amountMinor} currency={item.currency} type={item.type}/></td><td>{onSelect&&<ChevronRight size={17}/>}</td></tr>)}</tbody></table>:<p className={styles.empty}>No transactions to show.</p>;
}
export type TransactionsScreenProps={items:readonly TransactionTableItem[];query:string;month:string;typeFilter:string;currency:string;totalExpense:bigint;totalIncome:bigint;transactionCount:number;expenseCount:number;incomeCount:number;previousTotalExpense?:bigint;previousTotalIncome?:bigint;previousExpenseCount?:number;loading?:boolean;error?:string|null;rangeError?:string;onQueryChange:(value:string)=>void;onMonthChange:(value:string)=>void;onTypeFilterChange:(value:string)=>void;onSelect:(id:string)=>void;onCreate:()=>void};
export function TransactionsScreen(p:TransactionsScreenProps){const average=p.expenseCount?p.totalExpense/BigInt(p.expenseCount):0n;const previousAverage=p.previousExpenseCount&&p.previousExpenseCount>0?p.previousTotalExpense!/BigInt(p.previousExpenseCount):undefined;const metrics=[{label:'Total spending',value:<Money amountMinor={p.totalExpense} currency={p.currency}/>,note:compareTransactionAmounts(p.totalExpense,p.previousTotalExpense,true),fallback:`${p.currency} · selected month`,icon:ArrowDownRight},{label:'Total income',value:<Money amountMinor={p.totalIncome} currency={p.currency}/>,note:compareTransactionAmounts(p.totalIncome,p.previousTotalIncome,false),fallback:`${p.currency} · selected month`,icon:ArrowUpRight},{label:'Transactions',value:p.transactionCount,note:null,fallback:`${p.expenseCount} expenses · ${p.incomeCount} income`,icon:Wallet},{label:'Average expense',value:<Money amountMinor={average} currency={p.currency}/>,note:compareTransactionAmounts(average,previousAverage,true),fallback:`${p.currency} expenses`,icon:BarChart3}];return <main className={styles.page}><header className={styles.header}><div><h1 className={styles.heading}>Transactions</h1><p className={styles.subtitle}>All your transactions in one place.</p></div><div className={styles.controls}><label className={styles.search}><Search size={19}/><input className={styles.input} aria-label="Search transactions" placeholder="Search transactions…" value={p.query} onChange={e=>p.onQueryChange(e.target.value)}/></label><select aria-label="Filter transactions by type" value={p.typeFilter} onChange={e=>p.onTypeFilterChange(e.target.value)}><option value="all">Filters · All types</option><option value="expense">Expenses</option><option value="income">Income</option><option value="transfer">Transfers</option><option value="refund">Refunds</option><option value="adjustment">Adjustments</option></select><input type="month" className={styles.input} aria-label="Transaction month" value={p.month} onChange={e=>{if(/^\d{4}-\d{2}$/.test(e.target.value))p.onMonthChange(e.target.value);}}/></div></header><section className={styles.metrics} aria-label="Transaction totals">{metrics.map(({label,value,note,fallback,icon:Icon})=><div className={styles.metric} key={label}><span className={styles.tile}><Icon size={29}/></span><div><p>{label}</p><strong>{value}</strong><small data-tone={note?.tone}>{note?.label??fallback}</small></div></div>)}</section>{p.error&&<p role="alert" className={styles.error}>{p.error}</p>}{p.rangeError&&<p role="status" className={styles.help}>{p.rangeError}</p>}<section className={styles.tablePanel} aria-label="Transactions">{p.loading?<p className={styles.empty} role="status">Loading transactions…</p>:<TransactionTable items={p.items} onSelect={p.onSelect}/>}</section><button className={styles.fab} onClick={p.onCreate} aria-label="Add transaction"><Plus size={30}/></button></main>}
