import React from 'react';
import { ScrollView, View, Pressable } from 'react-native';
import { Button, Input, Text, Typography, useTheme } from '@finapp/ui/native';
import { CategoryIcon } from './CategoryIcon';
import { Money } from './Money';
import type { TransactionsScreenProps, TransactionTableItem } from '../web/TransactionsScreen';
export type { TransactionsScreenProps, TransactionTableItem } from '../web/TransactionsScreen';
export function TransactionCards({items,onSelect}: {items:readonly TransactionTableItem[];onSelect?:(id:string)=>void}) {
 const {tokens}=useTheme();return <View style={{gap:0}}>{items.length?items.map((item,index)=><Pressable key={item.id} accessibilityRole={onSelect?'button':undefined} onPress={()=>onSelect?.(item.id)} style={({pressed})=>({paddingVertical:13,borderBottomWidth:index===items.length-1?0:1,borderColor:tokens.borderSubtle,opacity:pressed?.7:1,gap:7})}><View style={{flexDirection:'row',alignItems:'center',gap:10}}><CategoryIcon label={item.category} icon={item.categoryIcon}/><View style={{flex:1,gap:3}}><Text style={{fontWeight:'600'}}>{item.title}</Text>{(item.note||item.merchant)&&<Typography variant="caption">{item.note||item.merchant}</Typography>}</View><Money amountMinor={item.amountMinor} currency={item.currency} type={item.type}/></View><View style={{flexDirection:'row',justifyContent:'space-between',gap:8,paddingLeft:42}}><Typography variant="caption">{item.category} · {item.account??'Unassigned'}{item.destination?` → ${item.destination}`:''}</Typography><Typography variant="caption">{item.date}</Typography></View></Pressable>):<Typography variant="caption" style={{paddingVertical:24,textAlign:'center'}}>No transactions to show.</Typography>}</View>;
}
export function TransactionsScreen(p:TransactionsScreenProps){
 const {tokens}=useTheme();const [filters,setFilters]=React.useState(false);const panel={borderWidth:1,borderColor:tokens.borderSubtle,borderRadius:12,backgroundColor:tokens.surfaceRaised,padding:16};
 return <ScrollView style={{flex:1,backgroundColor:tokens.background}} contentContainerStyle={{padding:16,gap:16,paddingBottom:36}} keyboardShouldPersistTaps="handled"><View><Typography variant="title">Transactions</Typography><Typography variant="caption">All your transactions in one place.</Typography></View><View style={{flexDirection:'row',gap:10,alignItems:'center'}}><View style={{flex:1}}><Input accessibilityLabel="Search transactions" placeholder="Search transactions…" value={p.query} onChangeText={p.onQueryChange}/></View><Button size="sm" variant="outline" onPress={()=>setFilters(!filters)}>Filters</Button></View><Input accessibilityLabel="Transaction month YYYY-MM" placeholder="YYYY-MM" value={p.month} onChangeText={value=>{if(/^\d{4}-\d{2}$/.test(value))p.onMonthChange(value);}}/>{filters&&<View style={{flexDirection:'row',flexWrap:'wrap',gap:6}}>{['all','expense','income','transfer','refund','adjustment'].map(type=><Button size="sm" key={type} variant={type===p.typeFilter?'primary':'outline'} onPress={()=>p.onTypeFilterChange(type)}>{type[0]!.toUpperCase()+type.slice(1)}</Button>)}</View>}<View style={{flexDirection:'row',flexWrap:'wrap',gap:10}}>{[{label:'Total spending',value:<Money amountMinor={p.totalExpense} currency={p.currency}/>,note:p.currency},{label:'Total income',value:<Money amountMinor={p.totalIncome} currency={p.currency}/>,note:p.currency},{label:'Transactions',value:p.transactionCount,note:`${p.expenseCount} expenses · ${p.incomeCount} income`},{label:'Average expense',value:<Money amountMinor={p.expenseCount?p.totalExpense/BigInt(p.expenseCount):0n} currency={p.currency}/>,note:`${p.currency} expenses`}].map(m=><View key={m.label} style={{...panel,width:'48%',gap:7}}><Typography variant="caption">{m.label}</Typography><Text style={{fontSize:24,fontWeight:'600'}}>{m.value}</Text><Typography variant="caption">{m.note}</Typography></View>)}</View>{p.error&&<Text accessibilityRole="alert" style={{color:tokens.expense}}>{p.error}</Text>}{p.rangeError&&<Typography variant="caption">{p.rangeError}</Typography>}<View style={panel}>{p.loading?<Typography variant="caption">Loading transactions…</Typography>:<TransactionCards items={p.items} onSelect={p.onSelect}/>}</View><Button onPress={p.onCreate}>Add transaction</Button></ScrollView>;
}
